/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author PNC2
 */
public class store extends javax.swing.JFrame {

    DB db;
    DBCollection collect;
    BasicDBObject backup;

    MongoClient mongo;
    MongoDatabase dbconnection;
    MongoCollection<org.bson.Document> collection;

    public store() {
        initComponents();
        setLocationRelativeTo(null);

        disable();
        disablelabel();

        delete.setVisible(false);

        addtocart1.setVisible(true);

        addedtable.setVisible(false);

        buynow.setVisible(false);

        box2.setVisible(false);
        box3.setVisible(false);
        box4.setVisible(false);

        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        keyboard1.setVisible(false);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        headset1.setVisible(false);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        mat1.setVisible(false);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);
    }

    public void data(String kuhn) {
        Login h = new Login();
        h.unameget();

        profname1.setText(kuhn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        sideline = new javax.swing.JLabel();
        box4 = new javax.swing.JPanel();
        i16 = new javax.swing.JLabel();
        i17 = new javax.swing.JLabel();
        i18 = new javax.swing.JLabel();
        i19 = new javax.swing.JLabel();
        i20 = new javax.swing.JLabel();
        lowerbg3 = new javax.swing.JLabel();
        box1 = new javax.swing.JPanel();
        i1 = new javax.swing.JLabel();
        i2 = new javax.swing.JLabel();
        i3 = new javax.swing.JLabel();
        i4 = new javax.swing.JLabel();
        i5 = new javax.swing.JLabel();
        lowerbg = new javax.swing.JLabel();
        box2 = new javax.swing.JPanel();
        i6 = new javax.swing.JLabel();
        i7 = new javax.swing.JLabel();
        i8 = new javax.swing.JLabel();
        i9 = new javax.swing.JLabel();
        i10 = new javax.swing.JLabel();
        lowerbg1 = new javax.swing.JLabel();
        box3 = new javax.swing.JPanel();
        i11 = new javax.swing.JLabel();
        i12 = new javax.swing.JLabel();
        i13 = new javax.swing.JLabel();
        i14 = new javax.swing.JLabel();
        i15 = new javax.swing.JLabel();
        lowerbg2 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        addedtable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        profname1 = new javax.swing.JLabel();
        buynow = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        addtocart1 = new javax.swing.JLabel();
        addtocart2 = new javax.swing.JLabel();
        addtocart3 = new javax.swing.JLabel();
        addtocart4 = new javax.swing.JLabel();
        addtocart5 = new javax.swing.JLabel();
        addtocart6 = new javax.swing.JLabel();
        addtocart7 = new javax.swing.JLabel();
        addtocart8 = new javax.swing.JLabel();
        addtocart9 = new javax.swing.JLabel();
        addtocart10 = new javax.swing.JLabel();
        addtocart11 = new javax.swing.JLabel();
        addtocart12 = new javax.swing.JLabel();
        addtocart13 = new javax.swing.JLabel();
        addtocart14 = new javax.swing.JLabel();
        addtocart15 = new javax.swing.JLabel();
        addtocart16 = new javax.swing.JLabel();
        addtocart17 = new javax.swing.JLabel();
        addtocart18 = new javax.swing.JLabel();
        addtocart19 = new javax.swing.JLabel();
        addtocart20 = new javax.swing.JLabel();
        mat1 = new javax.swing.JLabel();
        mat2 = new javax.swing.JLabel();
        mat3 = new javax.swing.JLabel();
        mat4 = new javax.swing.JLabel();
        mat5 = new javax.swing.JLabel();
        headset1 = new javax.swing.JLabel();
        headset2 = new javax.swing.JLabel();
        headset3 = new javax.swing.JLabel();
        headset4 = new javax.swing.JLabel();
        headset5 = new javax.swing.JLabel();
        keyboard5 = new javax.swing.JLabel();
        keyboard1 = new javax.swing.JLabel();
        keyboard2 = new javax.swing.JLabel();
        keyboard3 = new javax.swing.JLabel();
        keyboard4 = new javax.swing.JLabel();
        mouse1 = new javax.swing.JLabel();
        mouse2 = new javax.swing.JLabel();
        mouse3 = new javax.swing.JLabel();
        mouse4 = new javax.swing.JLabel();
        mouse5 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side.setBackground(new java.awt.Color(153, 255, 153));
        side.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mainlogo.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        side.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 120, 90));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mouseicon.PNG"))); // NOI18N
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon2MouseClicked(evt);
            }
        });
        side.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 80, 60));

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboardicon.PNG"))); // NOI18N
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon4MouseClicked(evt);
            }
        });
        side.add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 80, 60));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headseticon.PNG"))); // NOI18N
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon1MouseEntered(evt);
            }
        });
        side.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 90, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cart (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        side.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accessories.PNG"))); // NOI18N
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon3MouseClicked(evt);
            }
        });
        side.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 80, 60));

        sideline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/side (1).png"))); // NOI18N
        sideline.setText("jLabel11");
        side.add(sideline, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 530));

        getContentPane().add(side, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 530));

        box4.setBackground(new java.awt.Color(255, 0, 0));
        box4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i16.setBackground(new java.awt.Color(102, 255, 204));
        i16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat1 (2).png"))); // NOI18N
        i16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i16MouseClicked(evt);
            }
        });
        box4.add(i16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        i17.setBackground(new java.awt.Color(102, 255, 204));
        i17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat2 (2).png"))); // NOI18N
        i17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i17MouseClicked(evt);
            }
        });
        box4.add(i17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 90, -1));

        i18.setBackground(new java.awt.Color(102, 255, 204));
        i18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat3 (2).png"))); // NOI18N
        i18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i18MouseClicked(evt);
            }
        });
        box4.add(i18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 90, 60));

        i19.setBackground(new java.awt.Color(102, 255, 204));
        i19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat4 (2).png"))); // NOI18N
        i19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i19MouseClicked(evt);
            }
        });
        box4.add(i19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 90, 60));

        i20.setBackground(new java.awt.Color(102, 255, 204));
        i20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat5 (2).png"))); // NOI18N
        i20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i20MouseClicked(evt);
            }
        });
        box4.add(i20, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 10, 90, 60));

        lowerbg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lowerbg2.jpg"))); // NOI18N
        lowerbg3.setText("jLabel6");
        box4.add(lowerbg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 6, 570, 70));

        getContentPane().add(box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 80));

        box1.setBackground(new java.awt.Color(255, 0, 0));
        box1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i1.setBackground(new java.awt.Color(102, 255, 204));
        i1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2 (1).png"))); // NOI18N
        i1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i1MouseClicked(evt);
            }
        });
        box1.add(i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 66, -1));

        i2.setBackground(new java.awt.Color(102, 255, 204));
        i2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1(1).png"))); // NOI18N
        i2.setText("sdf");
        i2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i2MouseClicked(evt);
            }
        });
        box1.add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 66, -1));

        i3.setBackground(new java.awt.Color(102, 255, 204));
        i3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3(1).png"))); // NOI18N
        i3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i3MouseClicked(evt);
            }
        });
        box1.add(i3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 66, 60));

        i4.setBackground(new java.awt.Color(102, 255, 204));
        i4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4 (2).png"))); // NOI18N
        i4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i4MouseClicked(evt);
            }
        });
        box1.add(i4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 50, 60));

        i5.setBackground(new java.awt.Color(102, 255, 204));
        i5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5 (2).png"))); // NOI18N
        i5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i5MouseClicked(evt);
            }
        });
        box1.add(i5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 66, 60));

        lowerbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lowerbg2.jpg"))); // NOI18N
        lowerbg.setText("jLabel6");
        box1.add(lowerbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 6, 570, 70));

        getContentPane().add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 80));

        box2.setBackground(new java.awt.Color(255, 0, 0));
        box2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i6.setBackground(new java.awt.Color(102, 255, 204));
        i6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k1 (2).png"))); // NOI18N
        i6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i6MouseClicked(evt);
            }
        });
        box2.add(i6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, -1));

        i7.setBackground(new java.awt.Color(102, 255, 204));
        i7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k2 (2).png"))); // NOI18N
        i7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i7MouseClicked(evt);
            }
        });
        box2.add(i7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, -1));

        i8.setBackground(new java.awt.Color(102, 255, 204));
        i8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k3 (2).png"))); // NOI18N
        i8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i8MouseClicked(evt);
            }
        });
        box2.add(i8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 60));

        i9.setBackground(new java.awt.Color(102, 255, 204));
        i9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k4 (2).png"))); // NOI18N
        i9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i9MouseClicked(evt);
            }
        });
        box2.add(i9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 50, 60));

        i10.setBackground(new java.awt.Color(102, 255, 204));
        i10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k5 (2).png"))); // NOI18N
        i10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i10MouseClicked(evt);
            }
        });
        box2.add(i10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 66, 60));

        lowerbg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lowerbg2.jpg"))); // NOI18N
        lowerbg1.setText("jLabel6");
        box2.add(lowerbg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 6, 570, 70));

        getContentPane().add(box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 80));

        box3.setBackground(new java.awt.Color(255, 0, 0));
        box3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        i11.setBackground(new java.awt.Color(102, 255, 204));
        i11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset1 (2).png"))); // NOI18N
        i11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i11MouseClicked(evt);
            }
        });
        box3.add(i11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        i12.setBackground(new java.awt.Color(102, 255, 204));
        i12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset2 (2).png"))); // NOI18N
        i12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i12MouseClicked(evt);
            }
        });
        box3.add(i12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 80, -1));

        i13.setBackground(new java.awt.Color(102, 255, 204));
        i13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset3 (2).png"))); // NOI18N
        i13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i13MouseClicked(evt);
            }
        });
        box3.add(i13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 66, 60));

        i14.setBackground(new java.awt.Color(102, 255, 204));
        i14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset4 (2).png"))); // NOI18N
        i14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i14MouseClicked(evt);
            }
        });
        box3.add(i14, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 10, -1, 60));

        i15.setBackground(new java.awt.Color(102, 255, 204));
        i15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset5 (2).png"))); // NOI18N
        i15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i15MouseClicked(evt);
            }
        });
        box3.add(i15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 66, 60));

        lowerbg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lowerbg2.jpg"))); // NOI18N
        lowerbg2.setText("jLabel6");
        box3.add(lowerbg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 6, 570, 70));

        getContentPane().add(box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, 80));

        main.setBackground(new java.awt.Color(204, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Description", "Price"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        addedtable.setViewportView(table);

        main.add(addedtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 350));

        profname1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        profname1.setForeground(new java.awt.Color(255, 0, 0));
        profname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        profname1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        main.add(profname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 110, 30));

        buynow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buynow.png"))); // NOI18N
        main.add(buynow, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 220, 60));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.PNG"))); // NOI18N
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        main.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 150, 80));

        name.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 0, 0));
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/i_login.png"))); // NOI18N
        main.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 40, 30));

        label1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Name :");
        main.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        label2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Description :");
        main.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        label3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Price :");
        main.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, -1));

        label4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Quantity :");
        main.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        label5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Total :");
        main.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        txt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        main.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 270, 40));

        txt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        main.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 270, 40));

        txt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        main.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 270, 40));

        txt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt4KeyReleased(evt);
            }
        });
        main.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 270, 40));

        txt5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        main.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 170, 40));

        addtocart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart1MouseClicked(evt);
            }
        });
        main.add(addtocart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart2MouseClicked(evt);
            }
        });
        main.add(addtocart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart3MouseClicked(evt);
            }
        });
        main.add(addtocart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart4MouseClicked(evt);
            }
        });
        main.add(addtocart4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart5MouseClicked(evt);
            }
        });
        main.add(addtocart5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart6MouseClicked(evt);
            }
        });
        main.add(addtocart6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart7MouseClicked(evt);
            }
        });
        main.add(addtocart7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart8MouseClicked(evt);
            }
        });
        main.add(addtocart8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart9MouseClicked(evt);
            }
        });
        main.add(addtocart9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart10MouseClicked(evt);
            }
        });
        main.add(addtocart10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart11MouseClicked(evt);
            }
        });
        main.add(addtocart11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart12MouseClicked(evt);
            }
        });
        main.add(addtocart12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart13MouseClicked(evt);
            }
        });
        main.add(addtocart13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart14MouseClicked(evt);
            }
        });
        main.add(addtocart14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart15MouseClicked(evt);
            }
        });
        main.add(addtocart15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart16MouseClicked(evt);
            }
        });
        main.add(addtocart16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart17MouseClicked(evt);
            }
        });
        main.add(addtocart17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart18MouseClicked(evt);
            }
        });
        main.add(addtocart18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart19MouseClicked(evt);
            }
        });
        main.add(addtocart19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        addtocart20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R (1).png"))); // NOI18N
        addtocart20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtocart20MouseClicked(evt);
            }
        });
        main.add(addtocart20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, 50));

        mat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat1 (1).png"))); // NOI18N
        main.add(mat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 470, 390));

        mat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat2 (1).png"))); // NOI18N
        main.add(mat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 470, 390));

        mat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat3 (1).png"))); // NOI18N
        main.add(mat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 470, 390));

        mat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat4 (1).png"))); // NOI18N
        main.add(mat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 470, 390));

        mat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pad/mat5 (1).png"))); // NOI18N
        main.add(mat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 470, 390));

        headset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset1 (1).png"))); // NOI18N
        main.add(headset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 440, 360));

        headset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset2 (1).png"))); // NOI18N
        main.add(headset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 440, 360));

        headset3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset3 (1).png"))); // NOI18N
        main.add(headset3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 440, 360));

        headset4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset4 (1).png"))); // NOI18N
        main.add(headset4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 440, 360));

        headset5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/headsets/headset5 (1).png"))); // NOI18N
        main.add(headset5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 440, 360));

        keyboard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k5 (1).png"))); // NOI18N
        main.add(keyboard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 500, 200));

        keyboard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k1 (1).png"))); // NOI18N
        main.add(keyboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 500, 200));

        keyboard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k2 (1).png"))); // NOI18N
        main.add(keyboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 500, 200));

        keyboard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k3 (1).png"))); // NOI18N
        main.add(keyboard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 500, 200));

        keyboard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/keyboard/k4 (1).png"))); // NOI18N
        main.add(keyboard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 500, 200));

        mouse1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2 ().png"))); // NOI18N
        main.add(mouse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 530, 360));

        mouse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1 ().png"))); // NOI18N
        main.add(mouse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 460, 360));

        mouse3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3().png"))); // NOI18N
        main.add(mouse3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 410, 390));

        mouse4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4 (1).png"))); // NOI18N
        main.add(mouse4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 450, 360));

        mouse5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5 (1).png"))); // NOI18N
        main.add(mouse5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 46, 630, 360));

        bg.setBackground(new java.awt.Color(153, 153, 153));
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg (2).jpg"))); // NOI18N
        main.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i2MouseClicked
        // TODO add your handling code here:
        mouse2.setVisible(true);
        mouse1.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        disable();
        addtocart2.setVisible(true);
    }//GEN-LAST:event_i2MouseClicked

    private void i1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i1MouseClicked
        // TODO add your handling code here:
        mouse1.setVisible(true);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        disable();
        addtocart1.setVisible(true);
    }//GEN-LAST:event_i1MouseClicked

    private void i3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i3MouseClicked
        // TODO add your handling code here:
        mouse3.setVisible(true);
        mouse2.setVisible(false);
        mouse1.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        disable();
        addtocart3.setVisible(true);
    }//GEN-LAST:event_i3MouseClicked

    private void i4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i4MouseClicked
        // TODO add your handling code here:
        mouse4.setVisible(true);
        mouse1.setVisible(false);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse5.setVisible(false);

        disable();
        addtocart4.setVisible(true);
    }//GEN-LAST:event_i4MouseClicked

    private void i5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i5MouseClicked
        // TODO add your handling code here:
        mouse5.setVisible(true);
        mouse1.setVisible(false);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);

        disable();
        addtocart5.setVisible(true);
    }//GEN-LAST:event_i5MouseClicked

    private void i6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i6MouseClicked
        // TODO add your handling code here:
        keyboard1.setVisible(true);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        disable();
        addtocart6.setVisible(true);
    }//GEN-LAST:event_i6MouseClicked

    private void i7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i7MouseClicked
        // TODO add your handling code here:
        keyboard2.setVisible(true);
        keyboard1.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        disable();
        addtocart7.setVisible(true);
    }//GEN-LAST:event_i7MouseClicked

    private void i8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i8MouseClicked
        // TODO add your handling code here:
        keyboard3.setVisible(true);
        keyboard2.setVisible(false);
        keyboard1.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        disable();
        addtocart8.setVisible(true);
    }//GEN-LAST:event_i8MouseClicked

    private void i9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i9MouseClicked
        // TODO add your handling code here:
        keyboard4.setVisible(true);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard1.setVisible(false);
        keyboard5.setVisible(false);

        disable();
        addtocart9.setVisible(true);
    }//GEN-LAST:event_i9MouseClicked

    private void i10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i10MouseClicked
        // TODO add your handling code here:
        keyboard5.setVisible(true);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard1.setVisible(false);

        disable();
        addtocart10.setVisible(true);
    }//GEN-LAST:event_i10MouseClicked

    private void icon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseClicked
        // TODO add your handling code here:

        disablelabel();
        delete.setVisible(false);
        addedtable.setVisible(false);

        addtocart1.setVisible(true);
        buynow.setVisible(false);

        box1.setVisible(true);
        box2.setVisible(false);
        box3.setVisible(false);
        box4.setVisible(false);

        mouse1.setVisible(true);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        keyboard1.setVisible(false);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        headset1.setVisible(false);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        mat1.setVisible(false);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);

    }//GEN-LAST:event_icon2MouseClicked

    private void i11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i11MouseClicked
        // TODO add your handling code here:

        headset1.setVisible(true);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        disable();
        addtocart11.setVisible(true);
    }//GEN-LAST:event_i11MouseClicked

    private void i12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i12MouseClicked
        // TODO add your handling code here:
        headset2.setVisible(true);
        headset1.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        disable();
        addtocart12.setVisible(true);
    }//GEN-LAST:event_i12MouseClicked

    private void i13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i13MouseClicked
        // TODO add your handling code here:
        headset3.setVisible(true);
        headset2.setVisible(false);
        headset1.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        disable();
        addtocart13.setVisible(true);
    }//GEN-LAST:event_i13MouseClicked

    private void i14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i14MouseClicked
        // TODO add your handling code here:
        headset4.setVisible(true);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset1.setVisible(false);
        headset5.setVisible(false);

        disable();
        addtocart14.setVisible(true);
    }//GEN-LAST:event_i14MouseClicked

    private void i15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i15MouseClicked
        // TODO add your handling code here:
        headset5.setVisible(true);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset1.setVisible(false);

        disable();
        addtocart15.setVisible(true);
    }//GEN-LAST:event_i15MouseClicked

    private void i16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i16MouseClicked
        // TODO add your handling code here:
        mat1.setVisible(true);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);

        disable();
        addtocart16.setVisible(true);
    }//GEN-LAST:event_i16MouseClicked

    private void i17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i17MouseClicked
        // TODO add your handling code here:
        mat2.setVisible(true);
        mat1.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);

        disable();
        addtocart17.setVisible(true);
    }//GEN-LAST:event_i17MouseClicked

    private void i18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i18MouseClicked
        // TODO add your handling code here:
        mat3.setVisible(true);
        mat2.setVisible(false);
        mat1.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);

        disable();
        addtocart18.setVisible(true);
    }//GEN-LAST:event_i18MouseClicked

    private void i19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i19MouseClicked
        // TODO add your handling code here:
        mat4.setVisible(true);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat1.setVisible(false);
        mat5.setVisible(false);

        disable();
        addtocart19.setVisible(true);
    }//GEN-LAST:event_i19MouseClicked

    private void i20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i20MouseClicked
        // TODO add your handling code here:
        mat5.setVisible(true);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat1.setVisible(false);

        disable();
        addtocart20.setVisible(true);
    }//GEN-LAST:event_i20MouseClicked

    private void icon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseClicked
        // TODO add your handling code here:
        disablelabel();
        delete.setVisible(false);
        addedtable.setVisible(false);

        addtocart6.setVisible(true);
        buynow.setVisible(false);

        box2.setVisible(true);
        box1.setVisible(false);
        box3.setVisible(false);
        box4.setVisible(false);

        keyboard1.setVisible(true);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        mouse1.setVisible(false);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        headset1.setVisible(false);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        mat1.setVisible(false);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);
    }//GEN-LAST:event_icon4MouseClicked

    private void icon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_icon1MouseEntered

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked
        // TODO add your handling code here:
        disablelabel();
        delete.setVisible(false);
        addedtable.setVisible(false);

        addtocart11.setVisible(true);
        buynow.setVisible(false);

        box3.setVisible(true);
        box2.setVisible(false);
        box1.setVisible(false);
        box4.setVisible(false);

        headset1.setVisible(true);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        mouse1.setVisible(false);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        keyboard1.setVisible(false);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        mat1.setVisible(false);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);
    }//GEN-LAST:event_icon1MouseClicked

    private void icon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseClicked
        // TODO add your handling code here:
        disablelabel();
        delete.setVisible(false);
        addedtable.setVisible(false);

        addtocart16.setVisible(true);
        buynow.setVisible(false);

        box4.setVisible(true);
        box2.setVisible(false);
        box3.setVisible(false);
        box1.setVisible(false);

        mat1.setVisible(true);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);

        mouse1.setVisible(false);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        keyboard1.setVisible(false);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        headset1.setVisible(false);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);
    }//GEN-LAST:event_icon3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Landing_Page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addtocart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart1MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {

            String name = "Gaming mice 1";
            String description = " Wireless , Bluetooth";
            String price = "999";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart1.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }

    }//GEN-LAST:event_addtocart1MouseClicked

    private void addtocart2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart2MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming mice 2";
            String description = "Wired,  Wireless , Bluetooth, RGB";
            String price = "1200";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart2.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart2MouseClicked

    private void addtocart3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart3MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming mice 3";
            String description = "Wired, Bluetooth, Color (blue)";
            String price = "1000";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart3.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart3MouseClicked

    private void addtocart4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart4MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming mice 4";
            String description = "Wired, Color (Red)";
            String price = "650";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart4.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart4MouseClicked

    private void addtocart5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart5MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming mice 5";
            String description = "Wired, Bluetooth, RBG";
            String price = "1000";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart5.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart5MouseClicked

    private void addtocart6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart6MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Keyboard 1";
            String description = "Wired, RBG";
            String price = "1200";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart6.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart6MouseClicked

    private void addtocart7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart7MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Keyboard 2";
            String description = "Wired, Color (Violet), Inpired by Transformer";
            String price = "1700";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart7.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart7MouseClicked

    private void addtocart8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart8MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Keyboard 3";
            String description = "Wired, RBG , Bloody";
            String price = "1200";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart8.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart8MouseClicked

    private void addtocart9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart9MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Keyboard 4";
            String description = "Wired, RBG , Comfortable Bloody";
            String price = "1300";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart9.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart9MouseClicked

    private void addtocart10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart10MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Keyboard 5";
            String description = "Wired, Wireless,  RBG ,Comfort Bloody";
            String price = "1900";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart10.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart10MouseClicked

    private void addtocart11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart11MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {;
            String name = "Gaming Headset 1";
            String description = "Wired, Bloody";
            String price = "800";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart11.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart11MouseClicked

    private void addtocart12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart12MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Headset 2";
            String description = "Wired, Bloody, RGB";
            String price = "950";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart12.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart12MouseClicked

    private void addtocart13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart13MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Headset 3";
            String description = "Wired,Comforatable Bloody, ";
            String price = "1200";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart13.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart13MouseClicked

    private void addtocart14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart14MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Headset 4";
            String description = "Wired, Bloody ";
            String price = "1000";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart14.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart14MouseClicked

    private void addtocart15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart15MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Headset 5";
            String description = "Wired Comforatable Bloody, ";
            String price = "1500";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart15.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart15MouseClicked

    private void addtocart16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart16MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Mousepad 1";
            String description = "Bloody Headshot";
            String price = "500";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart16.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart16MouseClicked

    private void addtocart17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart17MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Mousepad 2";
            String description = "Bloody Handprint";
            String price = "500";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart17.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart17MouseClicked

    private void addtocart18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart18MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Mousepad 3";
            String description = "Bloody Handprint";
            String price = "1200";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart18.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart18MouseClicked

    private void addtocart19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart19MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Mousepad 4";
            String description = "Bloody Handprint, Bloody Fire";
            String price = "500";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart19.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart19MouseClicked

    private void addtocart20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtocart20MouseClicked
        // TODO add your handling code here:
        String userid = profname1.getText();
        if (userid.isBlank()) {
            JOptionPane.showMessageDialog(null, "Please Log in your account!");
            new Login().setVisible(true);
            this.setVisible(false);
        } else {
            String name = "Gaming Mousepad 5";
            String description = "Bloody Handprint, Large";
            String price = "500";

            try {
                mongo = new MongoClient("localhost", 27017);
                dbconnection = mongo.getDatabase("BigData");
                collection = dbconnection.getCollection("listed");

                Document collecting = new Document();

                collecting.append("UserID", userid);
                collecting.append("Name", name);
                collecting.append("Description", description);
                collecting.append("Price", price);
                collection.insertOne(collecting);
                JOptionPane.showMessageDialog(null, "Item being added to the cart");
                addtocart20.setVisible(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_addtocart20MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        disable();
        disabbox();
        enalelabel();
        showlisted();
        delete.setVisible(true);
        buynow.setVisible(true);
        addedtable.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.rowAtPoint(evt.getPoint());
        txt1.setText(table.getValueAt(index, 0).toString());
        txt2.setText(table.getValueAt(index, 1).toString());
        txt3.setText(table.getValueAt(index, 2).toString());

    }//GEN-LAST:event_tableMouseClicked

    private void txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyReleased
        // TODO add your handling code here:
        int pri = Integer.parseInt(txt3.getText());
        int quantity = Integer.parseInt(txt4.getText());
        int total = quantity * pri;
        String v = String.valueOf(total);
        txt5.setText(v);
    }//GEN-LAST:event_txt4KeyReleased

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
        delete();

    }//GEN-LAST:event_deleteMouseClicked

    public final void disable() {
        addtocart1.setVisible(false);
        addtocart2.setVisible(false);
        addtocart3.setVisible(false);
        addtocart4.setVisible(false);
        addtocart5.setVisible(false);
        addtocart6.setVisible(false);
        addtocart7.setVisible(false);
        addtocart8.setVisible(false);
        addtocart9.setVisible(false);
        addtocart10.setVisible(false);
        addtocart11.setVisible(false);
        addtocart12.setVisible(false);
        addtocart13.setVisible(false);
        addtocart14.setVisible(false);
        addtocart15.setVisible(false);
        addtocart16.setVisible(false);
        addtocart17.setVisible(false);
        addtocart18.setVisible(false);
        addtocart19.setVisible(false);
        addtocart20.setVisible(false);

    }

    public void disabbox() {
        box1.setVisible(false);
        box2.setVisible(false);
        box3.setVisible(false);
        box4.setVisible(false);

        mouse1.setVisible(false);
        mouse2.setVisible(false);
        mouse3.setVisible(false);
        mouse4.setVisible(false);
        mouse5.setVisible(false);

        keyboard1.setVisible(false);
        keyboard2.setVisible(false);
        keyboard3.setVisible(false);
        keyboard4.setVisible(false);
        keyboard5.setVisible(false);

        headset1.setVisible(false);
        headset2.setVisible(false);
        headset3.setVisible(false);
        headset4.setVisible(false);
        headset5.setVisible(false);

        mat1.setVisible(false);
        mat2.setVisible(false);
        mat3.setVisible(false);
        mat4.setVisible(false);
        mat5.setVisible(false);
    }

    public final void disablelabel() {
        label1.setVisible(false);
        label2.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        txt1.setVisible(false);
        txt2.setVisible(false);
        txt3.setVisible(false);
        txt4.setVisible(false);
        txt5.setVisible(false);

    }

    public final void enalelabel() {
        label1.setVisible(true);
        label2.setVisible(true);
        label3.setVisible(true);
        label4.setVisible(true);
        label5.setVisible(true);
        txt1.setVisible(true);
        txt2.setVisible(true);
        txt3.setVisible(true);
        txt4.setVisible(true);
        txt5.setVisible(true);

    }

    public void delete() {
        String g = txt1.getText();
        String gg = txt2.getText();
        String ggg = txt3.getText();
        collect = db.getCollection("listed");

        BasicDBObject listdelete = new BasicDBObject();
        listdelete.put("Name", g);
        listdelete.put("Description", gg);
        listdelete.put("Price", ggg);
        collect.findAndRemove(listdelete);
        txt1.setText("");
        txt2.setText("");
        txt3.setText("");

        showlisted();
    }

    public void showlisted() {
        String indentity = profname1.getText();

        try {
            DBCursor cursor;
            db = mongo.getDB("BigData");
            DBCollection coll = db.getCollection("listed");
            cursor = coll.find();
            String[] columnNames = {"Name", "Description", " Price"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            while (cursor.hasNext()) {
                DBObject obj = cursor.next();
                String u = (String) obj.get("UserID");
                if (u.equals(indentity)) {
                    String listedid = (String) obj.get("id");
                    String n = (String) obj.get("Name");
                    String q = (String) obj.get("Description");
                    String p = (String) obj.get("Price");
                    model.addRow(new Object[]{n, q, p});
                    table.setModel(model);
                }

            }

            cursor.close();
        } catch (Exception ex) {
            System.out.println(ex);

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new store().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane addedtable;
    private javax.swing.JLabel addtocart1;
    private javax.swing.JLabel addtocart10;
    private javax.swing.JLabel addtocart11;
    private javax.swing.JLabel addtocart12;
    private javax.swing.JLabel addtocart13;
    private javax.swing.JLabel addtocart14;
    private javax.swing.JLabel addtocart15;
    private javax.swing.JLabel addtocart16;
    private javax.swing.JLabel addtocart17;
    private javax.swing.JLabel addtocart18;
    private javax.swing.JLabel addtocart19;
    private javax.swing.JLabel addtocart2;
    private javax.swing.JLabel addtocart20;
    private javax.swing.JLabel addtocart3;
    private javax.swing.JLabel addtocart4;
    private javax.swing.JLabel addtocart5;
    private javax.swing.JLabel addtocart6;
    private javax.swing.JLabel addtocart7;
    private javax.swing.JLabel addtocart8;
    private javax.swing.JLabel addtocart9;
    private javax.swing.JLabel bg;
    private javax.swing.JPanel box1;
    private javax.swing.JPanel box2;
    private javax.swing.JPanel box3;
    private javax.swing.JPanel box4;
    private javax.swing.JLabel buynow;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel headset1;
    private javax.swing.JLabel headset2;
    private javax.swing.JLabel headset3;
    private javax.swing.JLabel headset4;
    private javax.swing.JLabel headset5;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i10;
    private javax.swing.JLabel i11;
    private javax.swing.JLabel i12;
    private javax.swing.JLabel i13;
    private javax.swing.JLabel i14;
    private javax.swing.JLabel i15;
    private javax.swing.JLabel i16;
    private javax.swing.JLabel i17;
    private javax.swing.JLabel i18;
    private javax.swing.JLabel i19;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel i20;
    private javax.swing.JLabel i3;
    private javax.swing.JLabel i4;
    private javax.swing.JLabel i5;
    private javax.swing.JLabel i6;
    private javax.swing.JLabel i7;
    private javax.swing.JLabel i8;
    private javax.swing.JLabel i9;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel keyboard1;
    private javax.swing.JLabel keyboard2;
    private javax.swing.JLabel keyboard3;
    private javax.swing.JLabel keyboard4;
    private javax.swing.JLabel keyboard5;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel lowerbg;
    private javax.swing.JLabel lowerbg1;
    private javax.swing.JLabel lowerbg2;
    private javax.swing.JLabel lowerbg3;
    private javax.swing.JPanel main;
    private javax.swing.JLabel mat1;
    private javax.swing.JLabel mat2;
    private javax.swing.JLabel mat3;
    private javax.swing.JLabel mat4;
    private javax.swing.JLabel mat5;
    private javax.swing.JLabel mouse1;
    private javax.swing.JLabel mouse2;
    private javax.swing.JLabel mouse3;
    private javax.swing.JLabel mouse4;
    private javax.swing.JLabel mouse5;
    private javax.swing.JLabel name;
    public javax.swing.JLabel profname1;
    private javax.swing.JPanel side;
    private javax.swing.JLabel sideline;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    // End of variables declaration//GEN-END:variables
}
