/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student.Admin
 */
public final class User_Dashboard extends javax.swing.JFrame {

    DB db;
    DBCollection collect;

    MongoClient mongo;
    MongoDatabase dbconnection;
    MongoCollection<org.bson.Document> collection;

    public User_Dashboard() {
        initComponents();

        display();
        uname.setVisible(false);

        this.setLocationRelativeTo(null);
        dropdown1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropdown1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        productss = new javax.swing.JButton();
        uname = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        arrow = new javax.swing.JLabel();
        jdate = new javax.swing.JLabel();
        dropdown = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dropdown1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout (1).png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        dropdown1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 40));

        productss.setBackground(new java.awt.Color(0, 255, 255));
        productss.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        productss.setText("PRODUCTS");
        productss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productssMouseClicked(evt);
            }
        });
        dropdown1.add(productss, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        getContentPane().add(dropdown1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 120, 100));
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        btn1.setBackground(new java.awt.Color(255, 0, 0));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("PURCHASED PRODUCTS");
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 180, 40));

        btn2.setBackground(new java.awt.Color(255, 0, 0));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("ABOUT ");
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 140, 40));

        btn3.setBackground(new java.awt.Color(255, 0, 0));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("CONTACT US");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 140, 40));

        btn4.setBackground(new java.awt.Color(255, 0, 0));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("OUR TEAM");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 140, 40));

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrowback.png"))); // NOI18N
        arrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowMouseClicked(evt);
            }
        });
        getContentPane().add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jdate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 160, 20));

        dropdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profilelogo.png"))); // NOI18N
        dropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dropdownMousePressed(evt);
            }
        });
        getContentPane().add(dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Price", "Quantity", "Total Price", "Date Purchased"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 680, 320));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dash.jpg"))); // NOI18N
        bg.setText("jLabel1");
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_jLabel3MouseClicked

    private void productssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productssMouseClicked
        // TODO add your handling code here:
        store toko = new store();
        toko.profname1.setText(uname.getText());
        toko.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_productssMouseClicked

    private void dropdownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dropdownMousePressed
        // TODO add your handling code here:
        dropdown1.setVisible(true);
    }//GEN-LAST:event_dropdownMousePressed

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked
        // TODO add your handling code here:
        dropdown1.setVisible(false);
    }//GEN-LAST:event_bgMouseClicked

    private void arrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowMouseClicked
        // TODO add your handling code here:
        store back = new store();
        back.profname1.setText(uname.getText());
        back.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_arrowMouseClicked

    public void display() {
        String indentity = uname.getText();
        try {
            DBCursor cursor;
            db = mongo.getDB("BigData");
            DBCollection coll = db.getCollection("sold");
            cursor = coll.find();
            String[] columnNames = {"Name", "Price", "Quantity", "Total Price", " Date Purchased"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            while (cursor.hasNext()) {
                DBObject obj = cursor.next();
                String u = (String) obj.get("Username");
                if (u.equals(indentity)) {
                    String a = (String) obj.get("P_Name ");
                    String b = (String) obj.get("P_Price ");
                    String c = (String) obj.get("P_Quantity ");
                    String d = (String) obj.get("P_Total ");
                    String e = (String) obj.get("Date ");
                    model.addRow(new Object[]{a, b, c , d, e});
                    table.setModel(model);
                }

            }

            cursor.close();
        } catch (Exception ex) {
            System.out.println(ex);

        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrow;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel dropdown;
    private javax.swing.JPanel dropdown1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jdate;
    private javax.swing.JButton productss;
    private javax.swing.JTable table;
    public javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
